# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swiftuse_frameworks!
platform :ios, '8.0'
use_frameworks!

target ‘YZDemo’ do

end

